name: Find out what Sunghyun is listening to
on:
  #   schedule:
  #   - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  get-current-tracks:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rebase Before Running
        run: |
          git config pull.rebase true
          git pull
      - name: Get Current Tracks
        run: python3 now-playing.py
        env:
          APPLE_MUSIC_DEV_TOKEN: ${{ secrets.APPLE_MUSIC_DEV_TOKEN }}
          APPLE_MUSIC_USER_TOKEN: ${{ secrets.APPLE_MUSIC_USER_TOKEN }}
      - name: Commit as Bot
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add now-playing.json
          git diff-index --quiet HEAD || git commit -m "Update now-playing"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_SECRET }}
          branch: main
